#Program shortcuts
alias g="cd"
alias r="ranger"
alias v="vim-py3"
alias ZZ="exit"
alias cs=""
alias :wq="exit"
alias cls=""
alias clear=""
alias mkd="mkdir"
alias vim="vim-py3"
alias mtw="sudo sshfs -p PORTGOESHERE -o allow_other USERGOESHERE@192.168.0.100:/home/USERGOESHERE/ /mnt/thewired_server"
alias sshtw="ssh -X -p PORTGOESHERE USERGOESHERE@192.168.0.100"
alias sshre="ssh -p PORTGOESHERE USERGOESHERE@IPGOESHERE"
alias pub_sshtw="ssh -X USERGOESHERE@IPGOESHERE -p PORTGOESHERE"
alias pdfl="pdflatex"
alias svim="sudo vim-py3"
alias reba="source ~/.bash_aliases"
alias smci="sudo make clean install"
alias texb="cp /mnt/thewired_server/500GigDrive1/Documents/LaTeX/beamer.tex"
alias texa="cp /mnt/thewired_server/500GigDrive1/Documents/LaTeX/article.tex"
alias ncmpcpp="ncmpcpp -b ~/.config/ncmpcpp/bindings"
alias wifiscan="nmcli device wifi rescan"
alias gitc="git add .; git commit; git push"

#Editing configuration files
alias vxd="vim-py3 ~/.Xdefaults"
alias vba="vim-py3 ~/.bash_aliases"
alias vgd="sudo vim-py3 /etc/default/grub"
alias vnc="vim-py3 ~/.config/ncmpcpp/config"
alias vvrc="vim-py3 ~/.vimrc"
alias vbrc="vim-py3 ~/.bashrc"
alias vxi="vim-py3 ~/.xinitrc"
alias vi3c="vim-py3 ~/.config/i3/config"
alias vmpdc="vim-py3 ~/.config/mpd/mpd.conf"
alias vrrc="vim-py3 ~/.config/ranger/rc.conf"
alias vi3bc="vim-py3 ~/.config/i3blocks/config"
alias vrri="vim-py3 ~/.config/ranger/rifle.conf"

alias gS="cd ~/Scripts"
