"" Jump and remove next jump structure.
let @f='/<++>4x'

autocmd FileType php let @u='i<ul>o</ul>ÂÃ½aO'
autocmd FileType php let @l='I<li>A</li>ÂÃ½aj'
autocmd FileType php let @e='c<center></center>hhhhhhhhP'
autocmd FileType php let @c='c<code></code>bhhP'
autocmd FileType php let @i='c<img="">hP'
autocmd FileType php let @b='i<br>hhh'
autocmd FileType php let @m='c<b></b>hhhP'
autocmd FileType php let @p='c<p>M/kbkb</p>hhhP'
autocmd FileType php let @h='c<a href=""></a>hhhP'
autocmd FileType php let @z='c<h1></h1>hhhhhp/</hl'
autocmd FileType php let @x='c<h2></h2>bhhhp/</'
autocmd FileType php let @v='c<h3></3kbh3>hhhhP'
autocmd FileType php let @s='c<small></small>bblP'
