#sudo apt install liblua5.1-0-dev
#sudo apt install liblua5.2-dev
#sudo apt install liblua5.3-dev
#sudo apt install liblualib50-dev
#sudo apt install libluajit-5.1-dev
#sudo apt install libmutter-3-dev
#sudo apt install libmutter-3-dev
sudo apt install libax25-dev
#sudo apt install libtexlua52-dev
#sudo apt install libtexlua53-dev
#sudo apt install libtexluajit-dev
sudo apt install libukwm-1-dev
sudo apt install libukwm-1-dev
#sudo apt install libvlccore-dev
#sudo apt install libvulkan-dev
#sudo apt install perl-tk
#sudo apt install xemacs21-bin
#sudo apt install librust-lua52-sys-dev
#sudo apt install pike8.0-doc
#sudo apt install python-pycparser
#sudo apt install python3-pycparser
